# multistage image here

FROM pdsc_gpu_build:latest as pdsc_build

FROM base_image_gpu:latest

SHELL ["/bin/bash", "-c"]

ENV PYTHON_USER=${USER}

# delete installed miniconda env
RUN rm -rf /home/${PYTHON_USER}/miniconda

# copy miniconda from build-stage with compiled libraries
COPY --from=pdsc_build /home/${PYTHON_USER}/miniconda /home/${PYTHON_USER}/miniconda

# fix permissions 
RUN chown -R ${PYTHON_USER}:${PYTHON_USER} /home/${PYTHON_USER}/miniconda

########################
