version: '3'
services:
  rdatascience:
    image: rdsc_bayesian:latest
    # restart: unless-stopped
    ports:
    - "127.0.0.1:8786:8787" #rstudio
    # https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/README.md
    volumes:
    - ./volume:/home/rstudio/volume
    environment:
      - DISABLE_AUTH=true
    tty: true
